const wayBillList = [
    {
        path:'/wayBillList',
        name:'wayBillList',
        meta:{
            title:'运单列表',
            keepalive:true
        },
        title:'运单列表',
        component:()=>import('pages/wayBill/wayBillList')
    },
    {
        path:'/lateWayBillList',
        name:'lateWayBillList',
        meta:{
            title:'延迟配送运单列表',
            keepalive:true
        },
        title:'延迟配送运单列表',
        component:()=>import('pages/wayBill/lateWayBillList')
    },
    {
        path:'/transformList',
        name:'transformList',
        meta:{
            title:'车次列表',
            keepalive:true
        },
        title:'车次列表',
        component:()=>import('pages/wayBill/transformList')
    },
    {
        path:'/shippedCar',
        name:'shippedCar',
        meta:{
            title:'已发货车次',
            keepalive:true
        },
        title:'已发货车次',
        component:()=>import('pages/wayBill/shippedCar')
    },
    {
        path:'/orderDetail',
        name:'orderDetail',
        meta:{
            title:'运单详情',
            keepalive:true
        },
        title:'运单详情',
        component:()=>import('pages/wayBill/orderDetail')
    },
    {
        path:'/trainDetail',
        name:'trainDetail',
        meta:{
            title:'车次详情',
            keepalive:false
        },
        title:'车次详情',
        component:()=>import('pages/wayBill/trainDetail')
    },
    {
        path:'/allotOrderList',
        name:'allotOrderList',
        meta:{
            title:'城际配送运单',
            keepalive:true
        },
        title:'城际配送运单',
        component:()=>import('pages/wayBill/allotOrderList')
    },
    {
        path:'/allotTaskList',
        name:'allotTaskList',
        meta:{
            title:'城际配送车次',
            keepalive:true
        },
        title:'城际配送车次',
        component:()=>import('pages/wayBill/allotTaskList')
    },
    {
        path:'/allotTaskDetail',
        name:'allotTaskDetail',
        meta:{
            title:'城际配送车次明细',
            keepalive:false
        },
        title:'城际配送车次明细',
        component:()=>import('pages/wayBill/allotTaskDetail')
    },
    {
        path:'/sweepSortCar',
        name:'sweepSortCar',
        meta:{
            title:'扫单分车',
            keepalive:false
        },
        title:'扫单分车',
        component:()=>import('pages/wayBill/sweepSortCar')
    }
]

export default wayBillList