const customerConfigRoute = [
    {
        path:'/outboundOrderCus',
        name:'outboundOrderCus',
        meta:{
            title:'出库单',
            keepalive:true
        },
        title:'出库单',
        component:()=>import('pages/customerPage/outboundOrderCus')
    },
    {
        path:'/inboundOrderListCus',
        name:'inboundOrderListCus',
        meta:{
            title:'入库单',
            keepalive:true
        },
        title:'入库单',
        component:()=>import('pages/customerPage/inboundOrderListCus')
    },
    {
        path:'/waveListCus',
        name:'waveListCus',
        meta:{
            title:'波次列表',
            keepalive:true
        },
        title:'波次列表',
        component:()=>import('pages/customerPage/waveListCus')
    },
    {
        path:'/pickTaskListCus',
        name:'pickTaskListCus',
        meta:{
            title:'拣货任务',
            keepalive:true
        },
        title:'拣货任务',
        component:()=>import('pages/customerPage/pickTaskListCus')
    },
    {
        path:'/commonOrderListCus',
        name:'commonOrderListCus',
        meta:{
            title:'订单列表',
            keepalive:true
        },
        title:'订单列表',
        component:()=>import('pages/customerPage/commonOrderListCus')
    },
    {
        path:'/transformListCus',
        name:'transformListCus',
        meta:{
            title:'车次列表',
            keepalive:true
        },
        title:'车次列表',
        component:()=>import('pages/customerPage/transformListCus')
    },
    {
        path:'/wayBillListCus',
        name:'wayBillListCus',
        meta:{
            title:'运单列表',
            keepalive:true
        },
        title:'运单列表',
        component:()=>import('pages/customerPage/wayBillListCus')
    },
]

export default customerConfigRoute